apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        timestamp: {{ now | quote }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis/redis-stack
        imagePullPolicy: "IfNotPresent"
        envFrom:
          - configMapRef:
              name:  {{ include "educationplatform.fullname" . }}-env
          - secretRef:
              name: {{ include "educationplatform.fullname" . }}-env
        ports:
        - containerPort: 5432
          name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379