env:
  browser: true
  es2021: true
extends:
  - google
  - plugin:react/recommended
  - plugin:prettier/recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - unused-imports
rules: {
  require-jsdoc: off,
  react/prop-types: off,
  no-unused-vars: off,
  unused-imports/no-unused-imports: error,
  unused-imports/no-unused-vars: [
    warn,
    {
      vars: all,
      varsIgnorePattern: "^_",
      args: after-used,
      argsIgnorePattern: "^_"
    }
  ]
}
settings:
  react:
    version: detect
