env:
  browser: true
  es2021: true
extends:
  - google
  - plugin:react/recommended
  - plugin:prettier/recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules: {
  require-jsdoc: off,
  react/prop-types: off,
  no-unused-vars: off
}
settings:
  react:
    version: detect
