{{- if .Values.backend.migrations.enabled }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "educationplatform.fullname" . }}-migrations
  labels:
    {{- include "educationplatform.labels" . | nindent 4 }}
    pod: backend
spec:
  activeDeadlineSeconds: {{ .Values.backend.migrations.activeDeadlineSeconds }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
      - name: migrations
        image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
        command: ["/bin/bash"]
        args: ["-c", {{ .Values.backend.migrations.command }} ]
        envFrom:
          - secretRef:
              name: {{ include "educationplatform.fullname" . }}-env
          - configMapRef:
              name: {{ include "educationplatform.fullname" . }}-env
      restartPolicy: Never
  backoffLimit: {{ .Values.backend.migrations.backoffLimit }}
...
{{- end }}