apiVersion: v1
kind: Service
metadata:
  name: {{ include "educationplatform.fullname" . }}-backend
  labels:
    {{- include "educationplatform.labels" . | nindent 4 }}
    pod: backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
      nodePort: {{ .Values.backend.service.nodePort }}
      protocol: TCP
      name: {{ .Values.backend.service.name }}
  selector:
    {{- include "educationplatform.selectorLabels" . | nindent 4 }}
    pod: backend
