kind: Secret
apiVersion: v1
metadata:
  name: {{ include "educationplatform.fullname" . }}-env-migrations
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "4"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded,hook-failed
    {{- with .Values.secrets.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
data:
{{- range $key, $value := .Values.env.secret }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}