apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "educationplatform.fullname" . }}-frontend
  labels:
    {{- include "educationplatform.labels" . | nindent 4 }}
    pod: frontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "educationplatform.selectorLabels" . | nindent 6 }}
      pod: frontend
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        timestamp: {{ now | quote }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "educationplatform.selectorLabels" . | nindent 8 }}
        pod: frontend
    spec:
      serviceAccountName: default
      containers:
        - name: {{ .Chart.Name }}
          {{ if .Values.frontend.image.tag }}
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag | default .Chart.AppVersion }}"
          {{- else }}
          image: "{{ .Values.frontend.image.repository }}"
          {{- end }}
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name:  {{ include "educationplatform.fullname" . }}-env
            - secretRef:
                name: {{ include "educationplatform.fullname" . }}-env
          ports:
            - name: http
              containerPort: {{ .Values.frontend.service.targetPort }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            {{- omit .Values.livenessProbe "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            {{- omit .Values.readinessProbe "enabled" | toYaml | nindent 12 }}
          {{- end }}
          terminationMessagePolicy: FallbackToLogsOnError
