apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "educationplatform.fullname" . }}-celery-beat
  labels:
    {{- include "educationplatform.labels" . | nindent 4 }}
    pod: celery
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "educationplatform.selectorLabels" . | nindent 6 }}
      pod: celery
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        timestamp: {{ now | quote }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "educationplatform.selectorLabels" . | nindent 8 }}
        pod: celery
    spec:
      serviceAccountName: default
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{ if .Values.backend.image.tag }}
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag | default .Chart.AppVersion }}"
          {{- else }}
          image: "{{ .Values.backend.image.repository }}"
          {{- end }}
          command: {{ .Values.celery.beat_command }}
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name:  {{ include "educationplatform.fullname" . }}-env
            - secretRef:
                name: {{ include "educationplatform.fullname" . }}-env
          ports:
            - name: http
              containerPort: {{ .Values.backend.service.targetPort }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            {{- omit .Values.livenessProbe "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            {{- omit .Values.readinessProbe "enabled" | toYaml | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          terminationMessagePolicy: FallbackToLogsOnError
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
