kind: Secret
apiVersion: v1
metadata:
  name: {{ include "educationplatform.fullname" . }}-env
  annotations:
    {{- with .Values.secrets.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
data:
{{- range $key, $value := .Values.env.secret }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
