apiVersion: v1
kind: Service
metadata:
  name: educationplatform
  labels:
    {{- include "educationplatform.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - nodePort: 30500
      port: 8000
      protocol: TCP
      targetPort: 8000
{{/*    - port: {{ .Values.service.port }}*/}}
{{/*      targetPort: {{ .Values.service.targetPort }}*/}}
{{/*      protocol: TCP*/}}
{{/*      name: {{ .Values.service.name }}*/}}
  selector:
    {{- include "educationplatform.selectorLabels" . | nindent 4 }}
