"""add_course_chapter_welcome_message

Revision ID: 8310e731138e
Revises: b2629291047d
Create Date: 2023-08-30 23:36:37.171889

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8310e731138e"
down_revision = "b2629291047d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "coursechapter", sa.Column("welcome_message", sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("coursechapter", "welcome_message")
    # ### end Alembic commands ###
