"""add_is_active_to_user

Revision ID: b2629291047d
Revises: 7647e5d82cb7
Create Date: 2023-08-30 09:44:03.823933

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b2629291047d"
down_revision = "7647e5d82cb7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("is_active", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "is_active")
    # ### end Alembic commands ###
