"""add_mentor_relation

Revision ID: 7647e5d82cb7
Revises: ac09dc0c31e5
Create Date: 2023-08-04 17:50:52.966053

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7647e5d82cb7"
down_revision = "ac09dc0c31e5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("coursechapter", sa.Column("mentor_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "coursechapter", "user", ["mentor_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "coursechapter", type_="foreignkey")
    op.drop_column("coursechapter", "mentor_id")
    # ### end Alembic commands ###
