"""add_image_type

Revision ID: 7e347eaec4d0
Revises: 42840c55b4e5
Create Date: 2024-06-15 13:46:37.404896

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7e347eaec4d0"
down_revision = "42840c55b4e5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE datatype ADD VALUE 'IMAGE'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE datatype REMOVE VALUE 'IMAGE'")
    # ### end Alembic commands ###
