"""add_payment_number

Revision ID: 0145911bd831
Revises: b68e36783f13
Create Date: 2024-03-24 17:36:29.493476

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0145911bd831"
down_revision = "b68e36783f13"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("service_payment_number", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "service_payment_number")
    # ### end Alembic commands ###
