"""change_payment_number_type

Revision ID: 4b89768e0a22
Revises: 0145911bd831
Create Date: 2024-03-24 18:30:50.631220

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4b89768e0a22"
down_revision = "0145911bd831"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user", "service_payment_number", existing_type=sa.INTEGER(), type_=sa.Text(), existing_nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user", "service_payment_number", existing_type=sa.Text(), type_=sa.INTEGER(), existing_nullable=True
    )
    # ### end Alembic commands ###
