"""add_chat_type

Revision ID: 42840c55b4e5
Revises: b68e36783f13
Create Date: 2024-06-15 01:04:05.898469

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from src.schemas import ChatType

# revision identifiers, used by Alembic.
revision = "42840c55b4e5"
down_revision = "b68e36783f13"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    chat_type = postgresql.ENUM(ChatType, name="chattype")
    chat_type.create(op.get_bind(), checkfirst=True)
    op.add_column("chat", sa.Column("chat_type", chat_type, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chat", "chat_type")
    # ### end Alembic commands ###
