"""remove_has_subscription

Revision ID: 4b599d458678
Revises: d2042122e0ef
Create Date: 2023-07-23 16:39:26.354537

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4b599d458678"
down_revision = "d2042122e0ef"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "has_subscription")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("has_subscription", sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
