"""test

Revision ID: 7b2d8687bf13
Revises: 4b599d458678
Create Date: 2023-07-31 18:48:01.961323

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7b2d8687bf13"
down_revision = "4b599d458678"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("service_uuid", sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "service_uuid")
    # ### end Alembic commands ###
