"""test

Revision ID: ac09dc0c31e5
Revises: 7b2d8687bf13
Create Date: 2023-08-01 16:02:51.694545

"""

# revision identifiers, used by Alembic.
revision = "ac09dc0c31e5"
down_revision = "7b2d8687bf13"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
