"""init

Revision ID: c37ea1a80143
Revises:
Create Date: 2023-06-25 14:23:31.449108

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c37ea1a80143"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "course",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("color", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("passed_welcome_page", sa.Boolean(), nullable=True),
        sa.Column("time_on_platform", sa.Integer(), nullable=True),
        sa.Column("avatar", sa.Text(), nullable=True),
        sa.Column("fullname", sa.Text(), nullable=True),
        sa.Column("company", sa.Text(), nullable=True),
        sa.Column("job", sa.Text(), nullable=True),
        sa.Column("email", sa.Text(), nullable=True),
        sa.Column("hashed_password", sa.Text(), nullable=True),
        sa.Column("has_subscription", sa.Boolean(), nullable=True),
        sa.Column("end_of_subscription", sa.Date(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "coursechapter",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("kinescope_project_id", sa.Text(), nullable=True),
        sa.Column("course_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["course.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "chat",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("receive_time", postgresql.TIME(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("last_video", sa.Integer(), nullable=True),
        sa.Column("coursechapter_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["coursechapter_id"],
            ["coursechapter.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "theme",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("coursechapter_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["coursechapter_id"],
            ["coursechapter.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "message",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("datetime", sa.DateTime(), nullable=True),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column(
            "content_type", sa.Enum("TEXT", "VIDEO", name="datatype"), nullable=True
        ),
        sa.Column("chat_id", sa.Integer(), nullable=True),
        sa.Column("theme_id", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["chat_id"],
            ["chat.id"],
        ),
        sa.ForeignKeyConstraint(
            ["theme_id"],
            ["theme.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "video",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=True),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("link", sa.Text(), nullable=True),
        sa.Column("coursechapter_id", sa.Integer(), nullable=True),
        sa.Column("theme_id", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["coursechapter_id"],
            ["coursechapter.id"],
        ),
        sa.ForeignKeyConstraint(
            ["theme_id"],
            ["theme.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("video")
    op.drop_table("message")
    op.drop_table("theme")
    op.drop_table("chat")
    op.drop_table("coursechapter")
    op.drop_table("user")
    op.drop_table("course")
    # ### end Alembic commands ###
