"""add subscription type

Revision ID: d2042122e0ef
Revises: 2b3ab9780760
Create Date: 2023-07-23 16:03:51.200090

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from src.db.models import SubscriptionType

# revision identifiers, used by Alembic.
revision = "d2042122e0ef"
down_revision = "2b3ab9780760"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    subscription_type = postgresql.ENUM(SubscriptionType, name="subscriptiontype")
    subscription_type.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "user",
        sa.Column("subscription_type", subscription_type, nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    subscription_type = postgresql.ENUM(SubscriptionType, name="subscriptiontype")
    subscription_type.drop(op.get_bind())
    op.drop_column("user", "subscription_type")
    # ### end Alembic commands ###
